version: "2"

services:
  web:
    container_name: web

    build: .
    restart: always
    ports:
        - "5000:5000"
    env_file:
        - .env

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - /root/certs/:/data/letsencrypt/
        - /etc/letsencrypt/:/etc/letsencrypt/