version: "2"

services:
  web:
    container_name: web

    build: .
    restart: always
    ports:
        - "3000:3000"
    env_file:
        - .env

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/certs:/data/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /root/certs:/data/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/data/letsencrypt --email dylanfinn89@gmail.com --agree-tos --no-eff-email --staging -d dylanfinn.dev -d www.dylanfinn.dev

volumes:
  certbot-var: